namespace fexgen {
struct returns_guest_pointer {};
struct custom_host_impl {};
struct fixup_vtable_in_return {};

// Namespace/function annotation
struct guest_entrypoint_base {};
struct guest_entrypoint_custom : guest_entrypoint_base {};
struct guest_entrypoint_none : guest_entrypoint_base {};

// Namespace annotation
struct indirect_guest_calls {};

struct custom_guest_entrypoint {}; // TODO: Deprecate in favor of guest_entrypoint_custom annotation
struct generate_guest_symtable {}; // TODO: Deprecate. FOREACH_<namespace>_SYMBOL macros should be generated by default

struct callback_annotation_base {
    // Prevent annotating multiple callback strategies
    bool prevent_multiple;
};
struct callback_stub : callback_annotation_base {};
struct callback_guest : callback_annotation_base {};

} // namespace fexgen
